# Generated by Django 4.0.6 on 2022-07-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webLib', '0002_alter_book_options_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='ltrType',
            field=models.CharField(choices=[('c', 'other'), ('b', 'donestic'), ('a', 'foreign')], default='a', max_length=1, verbose_name='Тип литературы'),
        ),
    ]
