# Generated by Django 4.0.6 on 2022-07-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='The size')),
                ('cost', models.IntegerField(null=True, verbose_name='Price')),
                ('adr', models.CharField(default='Armavits Str', max_length=200, verbose_name='Addres')),
                ('bol', models.BooleanField(default=True, verbose_name='balcony')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='isActive',
            field=models.BooleanField(default=True, null=True, verbose_name='Active'),
        ),
    ]
